src/animator.js
src/view-slot.js

feat(anim): Add animator service
Adds an animator service which is meant to provide basic animation
support via CSS classes

feat(anim): Add animator service

---

src/view-compiler.js

fix(ViewCompiler) Internet Explorer specific issue

---

src/bindable-property.js

loop variable key was missing declaration

fix(BindableProperty): added missing declaration

---

src/decorators.js

added missing function parameter, target, to elementConfig method

fix(Decorators): add missing parameter target

---

src/element-config.js

load method should return a promise.

fix(ElementConfigResource): return promise in load

---

src/composition-engine.js

updated UseView to UseViewStrategy to match new name

fix(CompositionEngine): fix UseViewStrategy import

---

src/bindable-property.js

fix(templating): update to new bindingMode API

---

src/animation-event.js
src/animation-events.js

adds a constant providing all possible events to be raised by the concrete Animator implementations
part of issue https://github.com/aurelia/animator-css/issues/13

feat(anim): add animation events const

---

src/animator.js

add extra animator methods for extra functionality and for working with
JS based animators
fixes: https://github.com/aurelia/templating/issues/88

feat(animator): add extra animator methods

---

src/view-compiler.js
test/view-compiler.spec.js

fix(ViewCompiler): handle adjacent text nodes, clear class attributes containing interpolation expressions

---

src/view-compiler.js

Fixes aurelia/templating-resources#75

fix(ViewCompiler): handle undefined instruction attributes

---

src/bindable-property.js

fix(BindableProperty): use strict equality operators

---

src/animation-event.js

adds additional animation events, also incorporating new interface methods
fixes issue https://github.com/aurelia/templating/issues/111

feat(anim): additional animation events

---

src/view-strategy.js

Adds support for .ts views.

---

src/decorators.js

refactor(decorators): made method parameters optional

---

package.json
test/html-behavior.spec.js

@EisenbergEffect not sure if this is right- it's what I had to do to get the tests passing

chore(tests): initialize PAL

---

test/html-behavior.spec.js
test/view-slot.spec.js

Covers all except the content selector methods

chore(tests): add tests for view slot

---

src/controller.js

fix(Controller): handle scope inheritance in template part with repeat

---

src/child-observation.js

Fixes two typos that show up in docs.
Note I've signed the Contributor Agreement already, so merge at will! :shipit:

Very minor typo fix

---

src/element-events.js

Feature: Element Events
Class to be used along side Element inside the dependency container. 
Handles adding, removing, and dispatching element events

feat(element-events)

---

src/decorators.js

Type Error Corrected in code comment

---

src/templating-engine.js

Typo error corrected in  templating-engine.js

---

.eslintrc
src/element-config.js
src/module-analyzer.js
test/decorators.spec.js

Fixes for a few issues I found while perusing the code.

Minor fixes

---

src/bindable-property.js

fix(bindable-property): fix typo in comment

---

src/view.js
test/view.spec.js

fix(View): preserve bindingContext while unbinding

---

src/templating-engine.js
test/templating-engine.spec.js

https://github.com/aurelia/templating/issues/270

fix(templating-engine): allow for overrideContext in enhance

---

src/view-slot.js
test/view-slot.spec.js

Needed for: https://github.com/aurelia/templating-resources/pull/215.
Fixes: https://github.com/aurelia/templating-resources/issues/213.

feat(ViewSlot): moving Views across the slot

---

src/composition-transaction.js

refactor(composition-transaction): create promise in the right scope

---

doc/article/en-US/templating-custom-elements.md

Pull request fixes duplicate au-doc-section uid's under custom-element documentation

fix(doc-section-ids)

---

src/child-observation.js

fixes https://github.com/aurelia/templating/issues/379

fix(child-observation): initialize @children array before using it

---

src/view.js

fix(view) Ensure current is not null.

---

doc/article/en-US/templating-html-behaviors-introduction.md

doc: update templating-html-behaviors-introduction.md

---

doc/article/en-US/templating-basics.md

Two small commits which added a backslash and correctly relocated a backslash.

Documentation fixes

---

doc/article/en-US/templating-basics.md

Changes "you can lean more..." to "you can learn more..."

Fixes minor typo in templating-basics.md

---

doc/article/en-US/templating-dynamic-ui-composition.md

Added in a simple dynamic UI topic. Might possibly pad this out more later on if needed.

doc(templating): dynamic UI topic

---

src/view-factory.js

Cache `hasAttribute`, `getAttribute`, `setAttribute`
Issue: #508

refactor(view-factory): Avoid creating anonymous function for each anchor

---

doc/article/en-US/templating-custom-attributes.md

doc (templating-custom-attributes): text update

---

doc/article/en-US/templating-content-projection.md

Just spotted it in the issues a few times and it still gets me so maybe it will help others to clarify it.

Add explanation of limitation of slots

---

build/paths.js
src/composition-engine.js
src/swap-strategies.js

Is related to feature request [aurelia/templating-resources#264](https://github.com/aurelia/templating-resources/issues/264)

feat(SwapOrder) Concurrent enter/leave transitions

---

doc/article/en-US/templating-dynamic-ui-composition.md

Fixed grammar at couple of places

fix grammar

---

dist/aurelia-templating.d.ts
src/element-events.js
test/element-events.js

@EisenbergEffect I forgot to adjust typing file. Also i think it's safe to move from `Element | EventTarget` to only `EventTarget`

chore(ElementEvents): typing

---

doc/article/en-US/templating-basics.md

Added description with sample code of if-else binding using Aurelia.

doc(templating-basics): Added if-else template controller to docs

---

src/child-observation.js

fix(child-observation): unset property in unbind

---

src/view-slot.js

of ".remove" and ".removeMany"

fix(view-slot): fix return type

---

README.md
package.json
src/composition-engine.js
test/composition-engine.spec.js

resolves #632 
resolves aurelia/templating-resources#355
resolves aurelia/cli#902
@EisenbergEffect

fix(CompositionEngine): ensure bind() after finishing composition

---

src/view-strategy.js

@EisenbergEffect I missed this part. Thanks to @gimerstedt for pointing this out

fix(StaticViewStrategy): use DOM.Element instead of HTMLTemplateElement

---

doc/article/en-US/templating-basics.md
doc/article/en-US/templating-custom-attributes.md
doc/article/en-US/templating-custom-elements.md
test/view-strategy.spec.js

ref https://github.com/aurelia/templating/pull/647#issuecomment-427989601

fix(doc): fix html5 syntax
