aurelia/templating

- src/composition-engine.js
The current version throws an error when using a `<compose>` element with only the `view` attribute. This change resolves that error.
closes 6
> fix(composition-engine): fix syntax error

- src/view-slot.js
This change fixes a crash in `view-slot` when using templates containing no child elements. `nextElementSibling` returns `null`, not `undefined`.
> fix(view-slot): correct nextElementSibling null check

- src/view-slot.js
add null checks for case when firstChild is null.  this occurs when the aurelia-app attribute is in a child element of body instead of on the body element, for example
Fixes #34
> fix(view-slot): add firstChild null checks

- src/html-behavior.js
This makes sure a shadow root is created when using @useView in combination with @useShadowDOM
fixes: https://github.com/aurelia/templating/issues/66
> fix(useshadowdom-noview): Create a shadow root when @noView is used

- src/util.js
- src/view-slot.js
When the templates get loaded nextElementSibling is missing in IE. Added helper method to search through nextSiblings to get the next element.
Closes aurelia/animator-css#8
> fix(view-slot): add fallback for missing nextElementSibling

- src/decorators.js
- src/html-behavior.js
- test/decorators.spec.js
- test/html-behavior.spec.js
Add a second parameter to customAttribute decorator, that allow to
specify the default binding mode on a custom attribute.
> feat(customAttribute): enable defaultBindingMode for customAttribute

- src/bindable-property.js
- src/content-selector.js
- src/decorators.js
- src/view-engine.js
We were previously using `import core from core-js` which generates d.ts that do not match the corejs d.ts. This is now updated to `import * as core 'core-js'`, which resolves TypeScript compilation warnings.
closes aurelia/framework#177
> fix(templating): Use correct import for core-js

- src/decorators.js
For d.ts generation i have made defaultBindingMode property in customAttribute decorator as optional.
> d.ts fix - optional property defaultBindingMode

- src/bindable-property.js
Changes undefined to null to catch errors with nested compose / bindable
scenario
> fix(bindable): bindable cannot be undefined

- src/dom.js
- test/dom.spec.js
Related to #174 
When template markup does not include a template
wrapper, an error is now thrown which specifies how to
resolve the issue.
> feat(dom): check markup for <template> wrapper

- src/view-slot.js
index could have changed since method was initially called
Required for aurelia/templating-resource#112
> fix(view-slot): check index before removing

- src/child-observation.js
TypeScript seems to leave descriptor undefined, so using they key to determine what to actually get the metadata for. Using typeof instead of checking for existence because empty strings ('') are coerced to false, though that SHOULD never happen.
> fix(child, children): Determine actual target by key

- src/view-slot.js
- test/view-slot.spec.js
When you call `bind` on a ViewSlot, the bindingContext is stored on the slot itself so that optimizations can occur in future binds. This patch simply enforces the same behavior for the override context, so that similar optimizations can be made using that information.
**NOTE:** I ran into the need for this during implementation of a more performant grid implementation I'm working through with @jdanyow. Since each of my "views" in a particular set of rows (for an array view strategy) are, in fact, ViewSlots (each containing a view for the `<td>` cells), it would be incredibly useful for me to have this information in that context.
> feat(ViewSlot): save override context during binding for later eval

- doc/article/en-US/templating-custom-attributes.md
Removing the extraneous s at the end of attributes.
> doc(custom-attribute): fix typo

- doc/article/en-US/templating-custom-elements.md
Let's consider this a first draft of this documentation. 
Questions:
Are there any other topics that need to be covered in the "basics" documentation?
Should we add working examples to go along with the example code?
Is it okay that I'm planning on splitting custom element documentation out in to multiple files?
Why is "A Christmas Story" the greatest Christmas movie of all time, and how did I watch Top Gun while writing this, but come up with examples that didn't involve Maverick?
> doc(custom element): add custom element basics doc

- doc/article/en-US/templating-custom-attributes.md
This switches to a more idiomatic TypeScript syntax for assigning private properties.
> doc(custom-attribute): switch to automatic private constructor props

- src/view-slot.js
- test/view-slot.spec.js
One more thing required to work with: https://github.com/aurelia/templating-resources/pull/215.
Removing one-by-one in the for-loop caused some race-conditions when the method was invoked too fast (like in the dbmonster example). The reason was that the indicies were changing as views were being removed. Having a function similar to `removeAll` solves this problem. This is also why the input to the function is not a list of indicies, but the array of `View`'s themselves.
> feat(ViewSlot): allow removal of many views at once to avoid a race condition

- doc/article/en-US/templating-custom-attributes.md
- doc/article/en-US/templating-custom-elements.md
I realized that putting a dot after the file name in code samples was unnecessary, so I've removed them.
> doc(all): fix typos and formatting

- doc/article/en-US/templating-custom-elements.md
This could be merged now, but should still be considered a work-in-progress.
> doc(custom-element): surrogate behaviors and content projection

- src/view-compiler.js
- test/view-compiler.spec.js
- Minor refactoring of unit test spec to include a top-level `ViewCompiler` describe function and a new `compile` describe function which includes the validation test for this fix.
Resolves #385
> feat(view-compiler): compile empty templates

- build/paths.js
- src/module-analyzer.js
- src/view-engine-hooks-resource.js
Allows for generating ViewEngineHooks resources via convention or decorator.
Replaces https://github.com/aurelia/templating/pull/381.
> feat(view-engine-hooks-resource): Add ViewEngineHooksResource

- doc/article/en-US/templating-basics.md
Wrote a document outlining the basics of Aurelia templating, walking the user through writing a custom element in pure markup, adding in the ViewModel, binding behaviours, importing custom elements and binding to custom attributes, conditionals, repeaters, and event binding.
Re: Issue #338
> Write Templating Basics to resolve #338

- src/view-locator.js
`if (origin)` was always evaluating to true, because when no Origin is found, an [`unknownOrigin` object is returned](https://github.com/aurelia/metadata/blob/7f50c4cc55ef6c6bf00ae3ffe14d0f97a14ce39e/src/origin.js#L4).
Instead, checking for 'origin.moduleId' will revitalize the currently-dead ifs.
This should mean better and earlier error handling for situations like: https://github.com/aurelia/templating/issues/418
> fix(view-locator): check 'origin.moduleId' instead of 'origin'

- doc/article/en-US/templating-custom-elements.md
correction for https://github.com/aurelia/templating/commit/0f4f7ce320f20935061d427a19e62db8103dfc53
> doc(templating-custom-elements): fix ES6 code

- src/behavior-property-observer.js
fixes aurelia/binding#496, aurelia/binding#479, #363
Requires aurelia/task-queue#16
> fix(BehaviorPropertyObserver): publish immediately when TaskQueue already flushing

- src/decorators.js
viewResources decorator uses incorrect argument name in call to metadata.define()
> fix(viewResources) - argument name mismatch in call to metadata.define()

- src/decorators.js
The `resources` parameter was renamed in [this commit](https://github.com/aurelia/templating/commit/b4316233ff2b6365ae1796ba6c4e816e6d98d1b3), but the accompanying parameter comment was left unchanged.
> Fix incorrect parameter name in doc comment

- .vscode/settings.json
- src/view-compiler.js
This is a bug fix for [#56](https://github.com/aurelia/templating-binding/issues/56)
[#391](https://github.com/aurelia/validation/issues/391) depends on this bug fix.  It requires two-way binding to work in the case when we're binding using the `primaryProperty` syntax.
> Use default binding from primary property

- src/view-slot.js
in removeAll, check for undefined children before executing returnToCache
fixes issue https://github.com/aurelia/animator-css/issues/57
> fix(view-slot): check for undefined child

- src/decorators.js
- src/html-behavior.js
- src/module-analyzer.js
- test/html-behavior.spec.js
Allows to create aliases for custom attributes by providing an array of aliases to the customAttribute decorator, or by applying then on the targets static property aliases
> feat(aliases): aliases for custom attributes

- doc/article/en-US/templating-custom-attributes.md
I'm pretty sure the typescript example was wrong...
> Typo in Typescript example?

- dist/amd/aurelia-templating.js
- dist/aurelia-templating.js
- dist/commonjs/aurelia-templating.js
- dist/es2015/aurelia-templating.js
- dist/native-modules/aurelia-templating.js
- dist/system/aurelia-templating.js
- doc/article/en-US/templating-html-behaviors-introduction.md
- src/bindable-property.js
- src/html-behavior.js
- test/behaviors/derived-element.js
- test/inheritance.spec.js
This PR adds support for `@bindable` properties inherited from a base class in a custom element.
This has been asked for several times, the open issue for that being #463.
The way `HtmlBehaviorResource` is used by Aurelia is unfortunately not inheritance-friendly. For this reason, this PR is very narrow in scope:
- It only adds support for `@bindable` properties. No other aspect from the base `HtmlBehaviorResource` is propagated to descendant classes.
- It only applies to custom elements. Custom attributes could easily share the same code, but we would need to define how the default `value` property would works precisely.
Additionally, the following restrictions apply:
- The derived classes need their own `HtmlBehaviorResource` metadata. So be sure to have at least one `@bindable` or …
> Inherited bindable properties in custom elements

- src/view-compiler.js
Using `primaryProperty` on a `templateController` attribute results in infinite recursion.
The reason is that `instruction.originalAttrName` sole purpose is to be removed from the template but because `primaryProperty` override `attrName` with the option name, it doesn't remove the attribute from the template anymore, hence the loop.
I fixed this specific bug only.
**There are other usages of `attrName` in `view-compiler` and I find _highly suspicious_ that we should replace the real custom attribute name with one of its options property. This wouldn't happen when not using `primaryProperty` so smells very wrong to me. Someone with more templating knowledge than me should review these uses.**
If I'm correct about this being unwanted, another fix could be to not re-assign `attrName` rather …
> fix(primaryProperty): infinite recursion with template controller

- doc/article/en-US/templating-custom-elements.md
Changed closing tag from `reqire` to `require`.
> doc(surrogate-behaviors): fix minor typo in markup

- doc/article/en-US/templating-basics.md
The docs suggest that the compose element component should supply a view attribute and bind a path to a html file. The example is working, but it is very error prone.
This works as expected:
```<compose view-model="hello" view.bind="hello.html"></compose>```
But when the view is being retrieved from a different directory, it starts to give errors:
```<compose view-model="hello" view.bind="../hello.html"></compose>```
Gives an error like:
```ERROR [app-router] Error: Parser Error: Unexpected token . at column 1 in [xxx.html]```
The fix to this issue is to either remove the `.bind`:
```<compose view-model="hello" view="../hello.html"></compose>```
or add single quotes:
```<compose view-model="hello" view.bind="'../hello.html'"></compose>```
Edit: I could also explain this issue in the docs …
> docs) fixes issue in example for using compose

- doc/article/en-US/templating-custom-attributes.md
This fixes a typo in the custom attribute dynamic options documentation. The variable used in the last clause of the `switch` should be `newValue`
> Fix typo in the dynamicOptions example: value -> newValue

- src/view-engine.js
When `urlOrRegistryEntry` is of type `RegistryEntry` we end up with `[object Object]` as a key in the `loadContext.dependencies` after calling `loadContext.addDependency`.
@EisenbergEffect *Not sure* if using `urlOrRegistryEntry.address` is the correct fix. I found this accidentally while familiarizing myself with templating.
> fix(view-engine): use .address in case of RegistryEntry

- src/view-engine.js
fix #566
@EisenbergEffect I have some concerns about the fix, since `ViewEngine` *creates* and *initializes* the behavior instance:
- currently the relation is `au-slot` behavior instance per `ViewEngine` instance.
- defining the metadata changes this - now it's on the ` class SlotCustomAttribute`.
- is it supported use case to have more than one instance of `ViewEngine` in an app(`enhance`)?
- is it supported use case to have more than one apps running in parallel?
> fix(view-engine): define metadata for SlotCustomAttribute

- src/view-compiler.js
`BindableProperty.name` is the *camelCase* name, use  `BindableProperty.attribute` for the *kebab-case* name.
fix #576
> fix(view-compiler): use the hyphenated name of the primary property

- src/child-observation.js
In the case with a significant portion of children (>2000), the `n+1` computation of the splice index becomes a significant overhead. This fix bypasses this computation in the special case when the selector is *.
I was unable to reliably build the dist output - it seems to have too many changes...
Before:
After:
> perf(child-observation) handle fast special case for wildcard (*) selector

- doc/article/en-US/templating-basics.md
Added a note on using repeat.for with arrays.
Use the array methods instead of replacing array elements by index with `[]` if you want Aurelia to observe the changes.
> doc(templating-basics): Added a note on using repeat.for with arrays

- doc/article/en-US/templating-html-behaviors-introduction.md
add callout to reiterate bind callback stops initial call of change handlers fixes
fixes aurelia/framework#856
> doc(html-behaviors): add callout regarding bind callback

- dist/aurelia-templating.d.ts
- src/decorators.js
- src/view-locator.js
- src/view-resources.js
- src/view-strategy.js
- test/decorators.spec.js
- test/view-locator.spec.js
- test/view-resources.spec.js
- test/view-strategy.spec.js
Follow up PR of #614 to have consistency with `@inject` and `static inject` 
I'm not certain about `@resource`, could be a breaking change but I don't think it's in use outside of templating-resources
@EisenbergEffect
> feat(decorators): add decorators for view and resource config

- src/module-analyzer.js
- src/view-resources.js
- test/module-analyzer.spec.js
- test/view-resources.spec.js
This adds interop-ability between a static resource field / method and existing decorators
@EisenbergEffect
> feat(resources): interop with custom element / attribute decorators

- src/shadow-dom.js
With static resources / view registration, bootstrapping Aurelia can be done easier, and earlier. Change from immediately resolved `DOM.Element` to delayed injection. This also helps in some test scenarios where folks bootstrap and import this module at the same time, slot tests will fail.
@EisenbergEffect
> refactor(Slot): delay element injection

- src/view-slot.js
- test/view-slot.spec.js
fixes #590 , #541
Previously `returnToCache` flag was ignored when removing projected content, causing views to be left bound even removed.
@EisenbergEffect @jdanyow 
Edit:
Related:
- https://github.com/aurelia/templating-resources/issues/310
> fix(ShadowDOM): respect `returnToCache` flag

- src/composition-engine.js
- test/composition-engine.spec.js
I'm expecting regardless whether I use *moduleId* or *class* for `.viewModel` to get the same behaviour for instantiating the VM.
Currently if using a *class* and it has no registrations(@*transient*, etc.) or there is no resolver registered in the `.container`/`.childContainer`(from the `CompositionContext`) it will be instantiated and registered as singleton in the *root container*. In contrast when using *moduleId* the loaded *class* will be *auto registered* in the *child container*.
@bigopon is it intended?
> fix(composition-engine): align class and moduleId behaviour

- src/view-slot.js
- test/view-slot.spec.js
This is a fix related to [this issue](https://github.com/aurelia/templating/issues/541#issuecomment-416160922)
We noticed that some of our unbind's on components where not being called which caused a memory leak in our application. This pull request intends to fix this.
I'm not a 100% sure if this is the correct place to fix this issue and if it causes any different behaviour than intented.
> Fixed a memory leak where unbind was not called if view was already detached

- src/view-strategy.js
- test/view-strategy.spec.js
Add *formal* `.moduleId` - `'undefined'`, so that one does *not* get [assigned](https://github.com/aurelia/templating/blob/1.8.2/src/html-behavior.js#L207) later on.
@bigopon
> fix(StaticViewStrategy): set formal ".moduleId"

- src/view-strategy.js
- test/view-strategy.spec.js
When `.template` is `null` - `@view({template: null, dependencies: [SomeResource]})`, act as `NoViewStrategy` - process the dependencies and return `null` for factory.
`@view(null)` already works as `@noView`.
> fix(StaticViewStrategy): check for null template before compiling

- dist/aurelia-templating.d.ts
- doc/article/en-US/templating-custom-elements.md
- src/binding-language.js
- src/instructions.js
- src/templating-engine.js
- src/view-compiler.js
- src/view-factory.js
- test/util.js
- test/view-compiler.spec.js
- test/view-factory.spec.js
- test/view-slot.spec.js
[Base discussion](https://github.com/aurelia/templating-binding/issues/115)
This is a step 1 to support let element.
Step 2 will be in `templating-binding` with implementation of let expression classes, and `createLetExpressions` for binding language.
requires aurelia/templating-binding#117
```html
<template>
<let
msg.bind='message'
fun-message.bind='msg | fun'
no-fun-message.bind='msg | noFun'
sentence='Full name is: "${fullName}" and first name is "${firstName}" and last name is "${lastName}"'
literal-string='I am a literal stirng in let element. Triggered warning.'></let>
<div repeat.for='day of days'>
<let day-name.bind='day | toShort'></let>
<span>Day name: ${dayName}. Index: ${$index}</span>
</div>
</template>
```
> feat(Let): let element for computed property declaration

- doc/article/en-US/templating-custom-elements.md
It appears that the examples of the usage of the let element don't seem to work without a closing tag. Unfortunately a self closing tag doesn't seem to work either. So I have added closing tags to the let elements for now.
> Added a closing tag to the let elements

- src/view-compiler.js
- test/view-compiler.spec.js
On gitter:
> I'm seeing a few warning messages as a result of using the new let functionality. Not an issue - but is this pointing at a possible issue?
WARN Detected string literal in let bindings. Did you mean "auTargetId.bind=65" or "auTargetId=${65}" ?
from this code in a custom element.
<let interested.bind="important ? 'Important' : 'Interested'"></let>
Atm, `<let/>` gets transformed into an instruction target too early. Should delay until after binding language has finished creating the instructions. Thanks 
@EisenbergEffect 
Thanks to @MylesPenlington
> fix(Let): mark as target after creating instrutions

- src/view-strategy.js
- test/view-strategy.spec.js
Atm, when one of the exports in module is not a function, it fails for the wrong reason as it tries to access `.elementName` of resource, which is undefined. This PR fixes that. Also add a test to cover invalid deps.
> fix(static-view-strategy): correctly handles invalid resources

- src/element-events.js
- test/element-events.spec.js
ElementEvents.subscribe will set capture to true be default if not explicitely passed in argument. This is not the standard behavior of the native addEventListener() and confuses developers. This new options let you define the default behavior.
Fixes issue #657
> fix(ElementEvents): ElementEvents.defaultListenerOptions allows to set default options when subscribing to events

- karma.conf.js
When a test fails under Karma the console stacktrace contains incorrect line
numbers making debugging impossible.
Applying fix manually as described in https://github.com/chriscasola/karma/commit/67d1cfe5bc4a85c039bb4d8af36b366879aa6cc0
closes aurelia/templating#670
> fix(karma): add retainLines to babelPreprocessor

- build/tasks/lint.js
- karma.conf.js
- package.json
- src/child-observation.js
- test/child-observation.integration.spec.ts
- test/tsconfig.json
At the moment, in `unbind()` of `ChildObserverBinder`, it's always unset the value via
```ts
this.viewModel[this.property] = null;
```
This works for native shadow DOM, because it's always ensured to retrieve the value again during `bind()`, as it's safe to do so. Originally, we didn't have this, and it was my attempt of trying to do proper cleanup, and it resulted in this subtle bug between native & emulation.
To actually fix it, the above needs to be nested inside a native shadow DOM usage check:
```ts
if (this.useShadowDOM) {
this.viewModel[this.property] = null;
}
``` 
For emulation, the content projection is done via an augmented view slot, and thus, can only work when content is actually projected through it, hence `.bind()`/`.unbind()` won't, and shouldn't affect it.
This PR also: …
> Fix: ensure child observation work properly with native & emulation for content projection 

- package-lock.json
- package.json
- src/view-resources.ts
This upgrade the minimum requirement for `aurelia-framework` dev dependency to `1.4.0`, allowing the vulv issue reported at https://github.com/aurelia/framework/issues/992 to be resolved.
> chore(dep): fix vuln issues with latest framework pkg
